// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PesquisaItensAPI.Data;

#nullable disable

namespace PesquisaItensAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230111195335_CriacaoDBTabelas")]
    partial class CriacaoDBTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PesquisaItensAPI.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("PesquisaItensAPI.Models.ItemPesquisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataPesquisa")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.Property<double>("PrecoFrete")
                        .HasColumnType("double");

                    b.Property<double>("PrecoPrazo")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemPesquisas");
                });

            modelBuilder.Entity("PesquisaItensAPI.Models.ItemPesquisa", b =>
                {
                    b.HasOne("PesquisaItensAPI.Models.Item", "Item")
                        .WithMany("ItemPesquisas")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PesquisaItensAPI.Models.Item", b =>
                {
                    b.Navigation("ItemPesquisas");
                });
#pragma warning restore 612, 618
        }
    }
}
